name: Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # 1. This step scans the repo. 
      # It will fail (block PR) only for High/Critical issues.
      # Low/Medium will be reported but won't stop the build.
      - name: Snyk test
        run: snyk test --all-projects --severity-threshold=high
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



      # 2. This step pushes the snapshot to your Snyk Dashboard
      # This ensures you don't have to import the project manually.
      - name: Snyk monitor
        run: snyk monitor --all-projects
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}