name: Snyk Security Scan

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Use 'continue-on-error' so the workflow doesn't stop if it finds bugs
      - name: Dependency Scan
        run: snyk test --all-projects --severity-threshold=high --org=alimottu0077
        continue-on-error: true

      - name: Code Scan
        run: snyk code test --all-projects --severity-threshold=high --org=alimottu0077
        continue-on-error: true

      - name: IaC Scan
        run: snyk iac test --all-projects --severity-threshold=high --org=alimottu0077
        continue-on-error: true

      # This step finally imports the project to your dashboard
      - name: Monitor Project (Import to Dashboard)
        run: snyk monitor --all-projects --org=alimottu0077